; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.
; Project uses delayed notes or cuts, you must set FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_awesomenes_part2=music_data_awesomenes_part2
.endif

music_data_awesomenes_part2:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : New song
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_awesomenes_part2
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env7,@env4,@env5,@env0 ; 00 : Kick
	.word @env6,@env4,@env5,@env0 ; 01 : Hat
	.word @env7,@env2,@env5,@env0 ; 02 : Snare
	.word @env1,@env4,@env5,@env0 ; 03 : Empty
	.word @env3,@env4,@env5,@env0 ; 04 : Melody

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$c0,$bf,$bf,$be,$00,$04
@env3:
	.byte $00,$cf,$c8,$c0,$00,$03
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $7f,$00,$00
@env6:
	.byte $00,$cf,$ce,$c8,$c5,$c2,$c0,$00,$06
@env7:
	.byte $00,$cf,$ce,$ca,$c6,$c4,$c3,$c2,$c1,$c0,$00,$09

@samples:

@song0ch0:
	.byte $46, $08
@song0ch0loop:
	.byte $ab, $86, $1d, $00, $1d, $00, $1d, $81, $00, $81, $1d, $00, $1d, $00, $1d, $81, $00, $81, $1d, $00, $20, $00, $19, $81
	.byte $00, $1b, $00, $50, $19, $29, $17, $8b, $00
@song0ref37:
	.byte $ff, $7f, $88
@song0ref40:
	.byte $22, $25, $25, $25, $25, $22, $22, $22, $22, $25, $81, $25, $81, $25, $83
	.byte $41, $0f
	.word @song0ref40
@song0ref58:
	.byte $22, $25, $25, $25, $25, $22, $22, $22, $22, $25, $81, $25, $81, $25, $81, $25, $22, $9d, $9f
	.byte $41, $0f
	.word @song0ref40
	.byte $41, $0f
	.word @song0ref40
	.byte $41, $11
	.word @song0ref58
	.byte $85, $00, $f5, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ab, $c1, $ff, $ff, $ff, $ff, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ab, $c1
	.byte $41, $10
	.word @song0ref37
	.byte $41, $0f
	.word @song0ref40
	.byte $41, $13
	.word @song0ref58
	.byte $41, $0f
	.word @song0ref40
	.byte $41, $0f
	.word @song0ref40
	.byte $41, $11
	.word @song0ref58
	.byte $85, $00, $f5, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $74, $86, $1d, $a9, $87, $73, $8f, $72, $8f, $71, $89, $00, $8d, $7f, $80, $15, $85, $15, $85, $15, $85, $15, $81, $84
	.byte $1a, $81, $80, $15, $85, $15, $85, $15, $85, $15, $81, $84, $1a, $81
@song0ref168:
	.byte $80, $15, $81, $7d, $82, $21, $81, $7f, $80, $15, $81, $7d, $82, $21, $81, $7f, $80, $15, $81, $7d, $82, $21, $81, $7f
	.byte $80, $15, $47, $0b, $7d, $82, $21, $84, $1a, $81, $7f
	.byte $41, $10
	.word @song0ref168
	.byte $7f
	.byte $41, $10
	.word @song0ref168
	.byte $7f
	.byte $41, $10
	.word @song0ref168
	.byte $7f
	.byte $41, $10
	.word @song0ref168
	.byte $7f
	.byte $41, $10
	.word @song0ref168
	.byte $7f
	.byte $41, $10
	.word @song0ref168
	.byte $7f
	.byte $41, $10
	.word @song0ref168
	.byte $7f
	.byte $41, $0f
	.word @song0ref168
	.byte $89, $00, $95, $ff, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ab, $c1, $ff, $ff, $ff, $ff, $42
	.word @song0ch4loop
